#!/bin/sh
touch /etc/config/kuainiao
# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@kuainiao[-1]
	add ucitrack kuainiao
	set ucitrack.@kuainiao[-1].init=kuainiao
	commit ucitrack
EOF
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
