include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for softethervpn
LUCI_PKGARCH:=all
LUCI_DEPENS:=+k3screenctrl

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
