#!/bin/sh
touch /etc/config/zerotier
# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@zerotier[-1]
	add ucitrack zerotier
	set ucitrack.@zerotier[-1].init=zerotier
	commit ucitrack
EOF
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
